# Generated by Django 5.2.2 on 2026-02-14 14:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('name', models.CharField(default='Untitled Travel Project', help_text='Travel Project for user', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the travel project', null=True)),
            ],
            options={
                'verbose_name': 'Travel Project',
                'verbose_name_plural': 'Travel Projects',
            },
        ),
    ]
