# Generated by Django 5.2.2 on 2026-02-14 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travelproject',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Project Owner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
