# Generated by Django 5.2.2 on 2026-02-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='name',
        ),
        migrations.AddField(
            model_name='place',
            name='title',
            field=models.CharField(default='Untitled Place', help_text='Title of the place', max_length=255),
        ),
    ]
