# Generated by Django 5.2.2 on 2026-02-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_remove_place_name_place_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='title',
        ),
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.CharField(default='Untitled Place', help_text='Name of the place', max_length=255),
        ),
    ]
