# Generated by Django 5.2.2 on 2026-02-14 14:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0003_remove_place_title_place_name'),
        ('travel_projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, help_text='Notes of the place', null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
                ('travel_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travel_projects.travelproject')),
            ],
            options={
                'verbose_name': 'Travel Place',
                'verbose_name_plural': 'Travel Places',
            },
        ),
    ]
