# Generated by Django 5.2.2 on 2026-02-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplace',
            name='is_visited',
            field=models.BooleanField(default=False, help_text='The place has been visited'),
        ),
    ]
