# Generated by Django 5.2.2 on 2026-02-16 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_places', '0002_travelplace_is_visited'),
        ('travel_projects', '0002_travelproject_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelplace',
            name='travel_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='travel_projects.travelproject'),
        ),
    ]
